version: '3.8'

services:
  app_notification:
    build: .
    container_name: fastapi_notification
    restart: always
    ports:
      - "8001:8001"
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: redis:latest
    container_name: redis_notification
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  redis_data:
    driver: local